### ISSUE TITLE
Bug in grouping clause

### ISSUE THREAD

**Issue by davidzhao800** [CS3201-2/SPA#101]
1 - bug
stmt s, s1; assign a;
Select s such that Follows(s1,s) and Parent_(s,a) and Modifies(s1, "peach") and Uses(s1, "peach") pattern a("banana", _"peach_9"_)
22
5000

All the clauses will be put into uselessOneVar

**Comment by comilao** [comment]
close with 3a122dbf5372fc8cc060647e02fe00aeba9675ef
