### ISSUE TITLE
bug in validator

### ISSUE THREAD

**Issue by comilao** [CS3201-2/SPA#103]
assign a1, a2; 
Select <a1, a2> pattern a1(_, _"1 + 4"_) and pattern a2(_, _"2 + 5"_)

**Comment by ManikaAgarwal** [comment]
The query is invalid. It can be 

assign a1, a2; 
Select pattern a1(_, _"1 + 4"_) and a2(_, _"2 + 5"_) 

or 

assign a1, a2; 
Select pattern a1(_, _"1 + 4"_) pattern a2(_, _"2 + 5"_)
