### ISSUE TITLE
bug with 'with' clause in query validator

### ISSUE THREAD

**Issue by comilao** [CS3201-2/SPA#104]
All of these queries was working well before I merged with your latest push today. I guess there is something wrong with 'with' clause. It is throwing an exception now. **ONE MORE THING, run all unit test as a regression testing before you push your code to master. It can't even pass some of the unit test**

assign a1, a2; variable v; stmt s1, s2;
Select <a1, a2> such that Follows(a1, a2) and Uses(a2, v) and Affects(a1, a2) with s1.stmt# = 3 and s2.stmt# = 4

assign a1, a2; stmt s; procedure p; variable v;
Select <p, s, v> such that Modifies(3, v) and Uses(4, v) with p.procName = "First"

assign a1, a2; stmt s; procedure p; variable v;
Select <p, s, v> such that Modifies(s, v) with p.procName = "First"

**Comment by ManikaAgarwal** [comment]
All three queries have no result clause. A query needs to have atleast one result clause.

**Comment by comilao** [comment]
Sorry, my fault. < and > are not displayed properly on Git Hub. 
You may try with a simple query like procedure p; Select p with p.procName = "First", it is also not working

**Comment by ManikaAgarwal** [comment]
Even that query is wrong. The query should be 

procedure p; Select p with p.procName = "First"

**Comment by comilao** [comment]
Oops, sorry. But you may try it with the query you just wrote.
procedure p; Select p with p.procName = "First"
You should be able to see that it is throwing an exception somewhere

**Comment by ManikaAgarwal** [comment]
fixed with 4dc02fb060affa267f1c67547c352cdd11ce300e
