### ISSUE TITLE
Timeout Queries

### ISSUE THREAD

**Issue by yeokangwei** [CS3201-2/SPA#106]
[SIMPLETest3 (With Line Numbers).txt](https://github.com/CS3201-2/SPA/files/25860/SIMPLETest3.With.Line.Numbers.txt)
[SIMPLETest3.txt](https://github.com/CS3201-2/SPA/files/25861/SIMPLETest3.txt)
[tempqueries3.txt](https://github.com/CS3201-2/SPA/files/25862/tempqueries3.txt)
[timeout.txt](https://github.com/CS3201-2/SPA/files/25863/timeout.txt)

**Comment by comilao** [comment]
close with fa991b95e10ab289fa381961262c7931c1e05039
