### ISSUE TITLE
Bug in Affects

### ISSUE THREAD

**Issue by yeokangwei** [CS3201-2/SPA#107]
SIMPLE code:
procedure First {
1       if x then {
2           while y {
3               x = y;
4               y = 2 + 3 + y;
5               y = 4 + 5;
            }
6           x = 1 + 2;
7           x = 1 + 3;
8           x = y + 1 + x;
        } else {
9           while z {
10              z = 1;
            }
        }
    }

Query:
1 - comment
assign a1, a2;
Select a1 such that Affects(a1, 8)
7
5000

Autotester reported 3, 6 and 7

[query.txt](https://github.com/CS3201-2/SPA/files/25877/query.txt)
[simple2.txt](https://github.com/CS3201-2/SPA/files/25878/simple2.txt)
[simple2 (With line numbers).txt](https://github.com/CS3201-2/SPA/files/25879/simple2.With.line.numbers.txt)

**Comment by luckyxkw** [comment]
fix with [b4d8e55]
