### ISSUE TITLE
Bug in Affects

### ISSUE THREAD

**Issue by yeokangwei** [CS3201-2/SPA#108]
SIMPLECode:
procedure Sixth {
    CHXOUD = 23 - 58;
    YTOID = 123 + 482;
    OFIEJ312 = NFOI341;
    NFOI341 = HFOISI;
    NFLJDJ43 = NFIEI341 + 5;
    while POSUD {
        VJFOUD = EQOUW - JFUD;
    }
    OFIEJ312 = NFOI341;
}
Query:
3 - comment
stmt s;
Select s such that Affects(s, 8)
4
5000

Autotester reports none but statement 4 affects statement 8
[bug1.txt](https://github.com/CS3201-2/SPA/files/25916/bug1.txt)
[query1.txt](https://github.com/CS3201-2/SPA/files/25917/query1.txt)

Simpler test case:
[bug1.txt](https://github.com/CS3201-2/SPA/files/25922/bug1.txt)
[query1.txt](https://github.com/CS3201-2/SPA/files/25921/query1.txt)

The bug could be due to a statement above modified statement which uses the variable.

**Comment by luckyxkw** [comment]
this has problem with query validator not with affect
