### ISSUE TITLE
Autotester crashes when invalid code is passed

### ISSUE THREAD

**Issue by ManikaAgarwal** [CS3201-2/SPA#109]
I actually discovered this bug by accident as my syntax was incorrect. The code I used was:

procedure yay {
    if a {
        jet = jet - jet;
        yay = yay + c;
    } else {
        call u;
    }
}

"then" is missing after "if a".

**Comment by comilao** [comment]
close with e7ed99001627e8cf1791f0bfe4fb7e4b2ee42958
