### ISSUE TITLE
validator substring type for pattern

### ISSUE THREAD

**Issue by comilao** [CS3201-2/SPA#110]
assign a; Select a pattern a(_, _"(f - d + b) - l"_)

log for the above query
Pattern clause: assign( _:all, (f - d + b) - l:)

I guess there should be a substring type for the second part of this pattern?

PS: If this issue is not your fault, assign back to me, I'll continue the investigation

**Comment by ManikaAgarwal** [comment]
fixed with 969fe13f1ecdc3e7ecd616b6abc42a79dc248d52

**Comment by comilao** [comment]
assign a; Select a pattern a(_, _"(d - p \* (t + p - l) \* j)"_)

assign a; Select a pattern a(_, _"(z - p) + l \* (a3 - s2) + f \* l \* (m \* i - w)"_)

assign a; Select a pattern a(_, _"(f - u - (p + c \* c) + c - f) \* (x \* j \* (g \* g - o) + u)"_)

**Comment by ManikaAgarwal** [comment]
All the queries work on my side.
