### ISSUE TITLE
Query Validator: bug

### ISSUE THREAD

**Issue by davidzhao800** [CS3201-2/SPA#122]
invalid query
[test.txt](https://github.com/CS3201-2/SPA/files/30605/test.txt)

**Comment by ManikaAgarwal** [comment]
Validator is correct. It is an invalid query. Correct query is:

assign a1;
Select a1 pattern a1(_,"c-(a-b_(c_(a-idx-(y-x))))")

**Comment by davidzhao800** [comment]
sorry, I put the wrong one

**Comment by davidzhao800** [comment]
ignore the \, should be underscore

**Comment by davidzhao800** [comment]
I upload a file for you

**Comment by ManikaAgarwal** [comment]
fixed with 69826b9a36ab1c08db90d20630b9debb1962e645
