### ISSUE TITLE
QueryProcessor: prog_line changed after iteration 2

### ISSUE THREAD

**Issue by davidzhao800** [CS3201-2/SPA#31]
In Iteration 1, prog_line must be a number, because we do not implement with clause, now the prog_line type is different;

**Comment by davidzhao800** [comment]
To clarify this: Modifies(3, "x") and  prog_line n; Modifies(n, "x") with n = 3;

**Comment by davidzhao800** [comment]
In addition, for withNAME clause: arg can be variable, call, string,  procedure
for withNUMBER clause: arg can be number, prog_line, constant, stmt(stmt, while, if, call, assign)

**Comment by davidzhao800** [comment]
For example Follows(23, 24), arg1Type is "number", 
prog_line n Follows(n, 24), arg1Type is "prog_line"

**Comment by davidzhao800** [comment]
Evaluator also need to change accordingly

**Comment by ManikaAgarwal** [comment]
done with df48b8d3d6fc14d033e02368ffe8d75d11695d54
