### ISSUE TITLE
get procedure id from call stmt

### ISSUE THREAD

**Issue by davidzhao800** [CS3201-2/SPA#32]
QueryEvaluator need an API
INTEGER getCallStmtProcedure ( INTEGER call_stmt_id );
return proc_id

**Comment by davidzhao800** [comment]
for example: 
5. Call "Sun";    (where "Sun" id is -1)
INTEGER getCallStmtProcedure( 5 ); should return -1

**Comment by comilao** [comment]
close with   e357e01
