### ISSUE TITLE
Bug in Next Table

### ISSUE THREAD

**Issue by yeokangwei** [CS3201-2/SPA#40]
procedure First {
1.  if a then {
2.      c = w + e;
3.      a = b + c;
    } else {
4.      b = c + d;
5.      if x then {
6.          x = x + y;
7.          y = z - x;
        } else {
8.          d = e - f;
        }
    }
}

Program Output:
next table
1:2 4 
2:3 
3:5 
4:6 
5:8 
6:7 
7:
8:

Correct me if I'm wrong, line 5 shouldn't be executed after line 3 right?
I think the correct output should be:
1: 2, 4
2: 3
3:
4: 5 
5: 6, 8
6: 7
7:
8:
![bug1](https://cloud.githubusercontent.com/assets/7575617/10366542/c049a814-6dfd-11e5-8cf6-3dce22351c2b.jpg)

**Comment by luckyxkw** [comment]
close with [d86af81]
