### ISSUE TITLE
Program crashes when call statement is exactly after container statement

### ISSUE THREAD

**Issue by yeokangwei** [CS3201-2/SPA#48]
![bug2](https://cloud.githubusercontent.com/assets/7575617/10420297/ed425272-70c2-11e5-89a2-99104a39292b.jpg)

![bug2b](https://cloud.githubusercontent.com/assets/7575617/10420360/b777b342-70c4-11e5-93d3-cae51fbcb4e6.jpg)

**Comment by comilao** [comment]
@yeokangwei  @Combat152 
Go to checker.cpp around line 270.
This line "procName = getProcName(stmtType, stmt);" should be moved above :

"if (!isValidName(procName)) {
                SPALog::log("invalid procName: " + stmt);
                return false;
            }"

**Comment by comilao** [comment]
close with b9a69d7e525f1f1351c15219acfedf6cd1399c0e
