### ISSUE TITLE
Output of multi-select

### ISSUE THREAD

**Issue by yeokangwei** [CS3201-2/SPA#57]
Eg. Select a, p … and the output of a is 10, 11, 13 and p is 1, 2
Return should be a list of strings; eg. “10 1”, “10 2”, “11 1”, “11 2”, “3 1”, “3 2”

There is a space between each number in the " ".

**Comment by comilao** [comment]
close with ba6c3c2e20ee7f7e4499c6fb2cf5c49b49341336
