### ISSUE TITLE
QueryEvaluator and QueryValidator assign pattern bug

### ISSUE THREAD

**Issue by davidzhao800** [CS3201-2/SPA#62]
should decide the attribute type from validator.
substring string?

**Comment by ManikaAgarwal** [comment]
I don't get what the bug is

**Comment by davidzhao800** [comment]
Now evaluator will detect the substring and string. I need to change

**Comment by ManikaAgarwal** [comment]
Alright, I thought Validator had a bug.

**Comment by davidzhao800** [comment]
change already

**Comment by davidzhao800** [comment]
[4cccf75]
