### ISSUE TITLE
Query Validator pattern bug

### ISSUE THREAD

**Issue by davidzhao800** [CS3201-2/SPA#70]
assign a; variable v; Select v such that Modifies(a, v) pattern a(_,"z+x+i")

pattern type is wrong. arg2Type is null
Log is like this:
assign( _:all, "z+x+i":) 

correct one should be 
assign( _:all, z+x+i:string)

**Comment by ManikaAgarwal** [comment]
fixed with ea578af0bc263747bc3e12589ed841aca81b89cc
