### ISSUE TITLE
Pattern bug

### ISSUE THREAD

**Issue by davidzhao800** [CS3201-2/SPA#76]
-1 : procedureMonday{
1  : callTuesday;
2  : apple=8;
3  : banana=apple+5;
4  : orange=5+apple_peach;
5  : ifpeachthen{
6  : callWednesday;
7  : apple=pear-1;
8  : whilestrawberry{
9  : apple=peach+pear_5+banana;
10 : peach=peach+1;}
11 : orange=apple;}
-1 : else{
12 : banana=16;}
13 : callFriday;}
-1 : procedureTuesday{
14 : ifstrawberrythen{
15 : callThursday;}
-1 : else{
16 : peach=20;
17 : whilebanana{
18 : apple=orange_7+banana_peach;
19 : peach=peach-1;}
20 : apple=strawberry;}}
-1 : procedureWednesday{
21 : peach=peach_apple;
22 : whilebanana{
23 : peach=banana+1;
24 : ifapplethen{
25 : banana=peach_9+16;}
-1 : else{
26 : banana=peach_9+5;}}}
-1 : procedureThursday{
27 : whileapple{
28 : whilebanana{
29 : apple=banana+1;}
30 : banana=0;}}
-1 : procedureFriday{
31 : pear=1;
32 : ifapplethen{
33 : apple=apple+1;
34 : ifstrawberrythen{
35 : strawberry=strawberry-1;}
-1 : else{
36 : peach=apple_banana+5+pear*orange;}}
-1 : else{
37 : peach=0;}}

pattern assign table
2: apple       ||||      .8;.
3: banana       ||||      .ap.
4: orange       ||||      .5..apple._+
7: apple       ||||      .pe.
9: apple       ||||      .peach..pear..5._+.ba.+
10: peach       ||||      .pea.
11: orange       ||||      ..
12: banana       ||||      .16;}.
16: peach       ||||      .20;.
18: apple       ||||      .orange..7._.banana..p._+
19: peach       ||||      .pea.
20: apple       ||||      .strawb.
21: peach       ||||      .peach..a.*
23: peach       ||||      .bana.
25: banana       ||||      .peach.
26: banana       ||||      .peac.
29: apple       ||||      .bana.
30: banana       ||||      .0;}}.
31: pear       ||||      .1;.
33: apple       ||||      .app.
35: strawberry       ||||      .str.
36: peach       ||||      .apple..banana._.5.+.pear..or._+
37: peach       ||||      .0;}}.

**Comment by comilao** [comment]
close with 8d4ba392f359403c00255779e8ad6f739c42b3cc
