### ISSUE TITLE
Bug in Pattern Right Hand Side Matching

### ISSUE THREAD

**Issue by yeokangwei** [CS3201-2/SPA#77]
SIMPLE code:

procedure First {
    q = z \* r + ((f - d + b) - l + r) - f + g;
}

Query:

1 - comment
assign a;
Select a pattern a(_, _"(f - d + b) - l"_)  <-Don't know why gitHub removed some underscores... The actual query is in the text file.
1
5000

[SIMPLEcode2.txt](https://github.com/CS3201-2/SPA/files/21442/SIMPLEcode2.txt)
[tempquery2.txt](https://github.com/CS3201-2/SPA/files/21443/tempquery2.txt)

**Comment by ManikaAgarwal** [comment]
fixed with c3ff175f4f09a46e544df46e0c217f92d6761561
