### ISSUE TITLE
bug in getting intermediate result

### ISSUE THREAD

**Issue by comilao** [CS3201-2/SPA#91]
procedure First {
    x = 1 + 4;
    x = 2 + 5;
    x = 3 + 6;
    y = x;
}

2 - comment
assign a, a1;
Select a such that Modifies(a1, "x") and Uses(a1, "x")
1, 2, 3, 4
5000

The intermediate resultTable for a1 is empty, evaluator returns none, which is not right.

**Comment by davidzhao800** [comment]
this can be solved using issue 92 and 93

**Comment by davidzhao800** [comment]
done by [387cd55]
