### ISSUE TITLE
Bug in Validator

### ISSUE THREAD

**Issue by yeokangwei** [CS3201-2/SPA#95]
Hi Manika!
Validator should accept stmtLst, as stated in pg 100 point 2 of handbook. StmtLst returns the first statement number in the list

SIMPLEcode:
procedure First {
    x = 1 + 4;
    x = 2 + 5;
    x = 3 + 6;
    y = x;
}

Query:
13 - comment  
assign a1, a2; stmtLst s;  
Select s such that Modifies(a1, "x") and Modifies(a2, "x") and Follows(a1, a2)
1
5000

**Comment by davidzhao800** [comment]
details: validator should support declaration like: stmtLst s; 
and select clause like select s;
nothing behind will be changed.

**Comment by ManikaAgarwal** [comment]
fixed with 354a78c04ed2975241cc99a8f56d9b9bf8cae9e3
