### ISSUE TITLE
Bug in Validator

### ISSUE THREAD

**Issue by comilao** [CS3201-2/SPA#96]
Below are the queries which are reported as invalid queries:

assign a;  Select a pattern a("x", _"x"_) such that Follows_(7,a)
assign a; while w; Select a pattern a("x", _"x"_) such that Follows_(w,7)
assign a; while w; Select a pattern a(_, _"haha"_) such that Parent*(w,a)

**Comment by ManikaAgarwal** [comment]
fixed with c655e8c2c43661fbea98e5f9240035e01fe53a78
